package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Goal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User ID")
   private int userid;
   @org.kie.api.definition.type.Label("Goal Name")
   private java.lang.String goalname;
   @org.kie.api.definition.type.Label("Target")
   private int target;
   @org.kie.api.definition.type.Label("Start")
   private int start;
   @org.kie.api.definition.type.Label("Low")
   private int low;
   @org.kie.api.definition.type.Label("High")
   private int high;
   @org.kie.api.definition.type.Label(value = "Program ID")
   private int programid;

   public Goal()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public java.lang.String getGoalname()
   {
      return this.goalname;
   }

   public void setGoalname(java.lang.String goalname)
   {
      this.goalname = goalname;
   }

   public int getTarget()
   {
      return this.target;
   }

   public void setTarget(int target)
   {
      this.target = target;
   }

   public int getStart()
   {
      return this.start;
   }

   public void setStart(int start)
   {
      this.start = start;
   }

   public int getLow()
   {
      return this.low;
   }

   public void setLow(int low)
   {
      this.low = low;
   }

   public int getHigh()
   {
      return this.high;
   }

   public void setHigh(int high)
   {
      this.high = high;
   }

   public int getProgramid()
   {
      return this.programid;
   }

   public void setProgramid(int programid)
   {
      this.programid = programid;
   }

   public Goal(int programid, int userid, java.lang.String goalname, int target, int start,
         int low, int high)
   {
      this.userid = userid;
      this.goalname = goalname;
      this.target = target;
      this.start = start;
      this.low = low;
      this.high = high;
      this.programid = programid;
   }

}
