package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Msg implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User ID")
   private int userid;
   @org.kie.api.definition.type.Label("Msg Name")
   private java.lang.String msgname;
   @org.kie.api.definition.type.Label("Msg Txt")
   private java.lang.String msgtxt;
   @org.kie.api.definition.type.Label(value = "Program ID")
   private int programid;

   public Msg()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public java.lang.String getMsgname()
   {
      return this.msgname;
   }

   public void setMsgname(java.lang.String msgname)
   {
      this.msgname = msgname;
   }

   public java.lang.String getMsgtxt()
   {
      return this.msgtxt;
   }

   public void setMsgtxt(java.lang.String msgtxt)
   {
      this.msgtxt = msgtxt;
   }

   public int getProgramid()
   {
      return this.programid;
   }

   public void setProgramid(int programid)
   {
      this.programid = programid;
   }

   public Msg(int programid, int userid, java.lang.String msgname,
         java.lang.String msgtxt)
   {
      this.userid = userid;
      this.msgname = msgname;
      this.msgtxt = msgtxt;
      this.programid = programid;
   }

}