package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OptInOut implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Program ID")
   private int programid;
   @org.kie.api.definition.type.Label("User ID")
   private int userid;
   @org.kie.api.definition.type.Label("Rule Name")
   private java.lang.String rulename;

   @org.kie.api.definition.type.Label("In or Out")
   private java.lang.String inorout;

   @org.kie.api.definition.type.Label("Group Name")
   private java.lang.String groupname;

   public OptInOut()
   {
   }

   public java.lang.String getRulename()
   {
      return this.rulename;
   }

   public void setRulename(java.lang.String rulename)
   {
      this.rulename = rulename;
   }

   public java.lang.String getInorout()
   {
      return this.inorout;
   }

   public void setInorout(java.lang.String inorout)
   {
      this.inorout = inorout;
   }

   public java.lang.String getGroupname()
   {
      return this.groupname;
   }

   public void setGroupname(java.lang.String groupname)
   {
      this.groupname = groupname;
   }

   public int getProgramid()
   {
      return this.programid;
   }

   public void setProgramid(int programid)
   {
      this.programid = programid;
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public OptInOut(int programid, int userid, java.lang.String rulename,
         java.lang.String inorout, java.lang.String groupname)
   {
      this.programid = programid;
      this.userid = userid;
      this.rulename = rulename;
      this.inorout = inorout;
      this.groupname = groupname;
   }

}