package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserFact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User ID")
   private int userid;
   @org.kie.api.definition.type.Label("Fact Name")
   private java.lang.String factname;
   @org.kie.api.definition.type.Label("Fact Txt")
   private java.lang.String facttxt;

   @org.kie.api.definition.type.Label(value = "Program ID")
   private int programid;

   public UserFact()
   {
   }

   public java.lang.String getFactname()
   {
      return this.factname;
   }

   public void setFactname(java.lang.String factname)
   {
      this.factname = factname;
   }

   public java.lang.String getFacttxt()
   {
      return this.facttxt;
   }

   public void setFacttxt(java.lang.String facttxt)
   {
      this.facttxt = facttxt;
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public int getProgramid()
   {
      return this.programid;
   }

   public void setProgramid(int programid)
   {
      this.programid = programid;
   }

   public UserFact(int programid, int userid, java.lang.String factname,
         java.lang.String facttxt)
   {
      this.userid = userid;
      this.factname = factname;
      this.facttxt = facttxt;
      this.programid = programid;
   }

}